# building container 
FROM registry.fedoraproject.org/fedora-minimal AS build 
RUN mkdir /invdsigner && microdnf install git rust cargo -y && microdnf clean all -y
WORKDIR /invdsigner 
COPY . /invdsigner
RUN cd /invdsigner && cargo build

FROM registry.fedoraproject.org/fedora-minimal 
WORKDIR / 
RUN ls -la / && ls -la /usr/local/bin 
COPY --from=build /invdsigner/target/debug/inventory-dsigner /usr/local/bin 
CMD ["inventory-dsigner"] 
EXPOSE 7878